apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-volume-controller
data:
  config.yml: |
    clusterServerCfg:
      masterURL:
      kubeConfig:
    veleroVolumeCfg:
      includeNamespaces: test
      excludeNamespaces:
      includeVolumeTypes: persistentVolumeClaim
      excludeVolumeTypes:
